# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MarvelAppUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelAppUIKit
  pod 'RealmSwift', '=10.1.4'

  target 'MarvelAppUIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelAppUIKitUITests' do
    # Pods for testing
  end

end
